// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetFlow.Infrastructure.Persistence;

#nullable disable

namespace VetFlow.Infrastructure.Migrations
{
    [DbContext(typeof(VetFlowContext))]
    partial class VetFlowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("VetFlow.Domain.Entities.Tutor", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<bool>("Active").HasDefaultValue(true).HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("CV_TUTORS");
            });

            modelBuilder.Entity("VetFlow.Domain.Entities.Clinic", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<bool>("Active").HasDefaultValue(true).HasColumnType("INTEGER");
                b.Property<string>("Address").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("TEXT");
                b.Property<string>("Email").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("CV_CLINICS");
            });

            modelBuilder.Entity("VetFlow.Domain.Entities.Pet", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<bool>("Active").HasDefaultValue(true).HasColumnType("INTEGER");
                b.Property<DateTime>("BirthDate").HasColumnType("TEXT");
                b.Property<string>("Breed").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Species").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<Guid>("TutorId").HasColumnType("TEXT");
                b.Property<double>("WeightKg").HasColumnType("REAL");
                b.HasKey("Id");
                b.HasIndex("TutorId");
                b.ToTable("CV_PETS");
            });

            modelBuilder.Entity("VetFlow.Domain.Entities.Appointment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<Guid>("ClinicId").HasColumnType("TEXT");
                b.Property<bool>("Completed").HasDefaultValue(false).HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("TEXT");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("TEXT");
                b.Property<Guid>("PetId").HasColumnType("TEXT");
                b.Property<DateTime>("ScheduledAt").HasColumnType("TEXT");
                b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ClinicId");
                b.HasIndex("PetId");
                b.ToTable("CV_APPOINTMENTS");
            });

            modelBuilder.Entity("VetFlow.Domain.Entities.Vaccine", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<DateTime>("AppliedAt").HasColumnType("TEXT");
                b.Property<string>("Batch").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("TEXT");
                b.Property<DateTime>("NextDoseAt").HasColumnType("TEXT");
                b.Property<Guid>("PetId").HasColumnType("TEXT");
                b.Property<string>("VaccineName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("PetId");
                b.ToTable("CV_VACCINES");
            });

            modelBuilder.Entity("VetFlow.Domain.Entities.Medication", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("TEXT");
                b.Property<string>("Dosage").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("EndDate").HasColumnType("TEXT");
                b.Property<string>("Frequency").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<Guid>("PetId").HasColumnType("TEXT");
                b.Property<DateTime>("StartDate").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasDefaultValue("ACTIVE").HasMaxLength(20).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("PetId");
                b.ToTable("CV_MEDICATIONS");
            });
#pragma warning restore 612, 618
        }
    }
}
